import React from "react";
// import HTMLFlipBook from "react-pageflip";
import HTMLFlipBook from "./HTMLFlipBookNav";

const QuranPageFlip = () => {
  // ✅ Define the page images in an array
  const pages = [
    process.env.PUBLIC_URL + "/quran/title.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-2.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-3.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-4.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-5.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-6.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-7.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-8.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-9.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-10.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-11.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-12.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-13.jpg",
    process.env.PUBLIC_URL + "/quran/para-1/page-14.jpg",

    process.env.PUBLIC_URL + "/quran/para-2/page-15.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-16.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-17.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-18.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-19.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-20.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-21.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-22.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-23.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-24.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-25.jpg",
    process.env.PUBLIC_URL + "/quran/para-2/page-26.jpg",

    process.env.PUBLIC_URL + "/quran/para-3/page-27.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-28.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-29.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-30.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-31.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-32.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-33.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-34.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-35.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-36.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-37.jpg",
    process.env.PUBLIC_URL + "/quran/para-3/page-38.jpg",

    process.env.PUBLIC_URL + "/quran/para-4/page-39.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-40.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-41.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-42.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-43.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-44.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-45.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-46.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-47.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-48.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-49.jpg",
    process.env.PUBLIC_URL + "/quran/para-4/page-50.jpg",

    process.env.PUBLIC_URL + "/quran/para-5/page-51.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-52.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-53.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-54.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-55.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-56.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-57.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-58.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-59.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-60.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-61.jpg",
    process.env.PUBLIC_URL + "/quran/para-5/page-62.jpg",

    process.env.PUBLIC_URL + "/quran/para-6/page-63.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-64.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-65.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-66.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-67.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-68.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-69.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-70.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-71.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-72.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-73.jpg",
    process.env.PUBLIC_URL + "/quran/para-6/page-74.jpg",

    process.env.PUBLIC_URL + "/quran/para-7/page-75.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-76.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-77.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-78.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-79.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-80.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-81.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-82.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-83.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-84.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-85.jpg",
    process.env.PUBLIC_URL + "/quran/para-7/page-86.jpg",

    process.env.PUBLIC_URL + "/quran/para-8/page-87.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-88.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-89.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-90.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-91.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-92.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-93.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-94.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-95.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-96.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-97.jpg",
    process.env.PUBLIC_URL + "/quran/para-8/page-98.jpg",

    process.env.PUBLIC_URL + "/quran/para-9/page-99.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-100.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-101.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-102.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-103.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-104.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-105.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-106.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-107.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-108.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-109.jpg",
    process.env.PUBLIC_URL + "/quran/para-9/page-110.jpg",

    process.env.PUBLIC_URL + "/quran/para-10/page-111.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-112.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-113.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-114.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-115.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-116.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-117.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-118.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-119.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-120.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-121.jpg",
    process.env.PUBLIC_URL + "/quran/para-10/page-122.jpg",

    process.env.PUBLIC_URL + "/quran/para-11/page-123.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-124.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-125.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-126.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-127.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-128.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-129.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-130.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-131.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-132.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-133.jpg",
    process.env.PUBLIC_URL + "/quran/para-11/page-134.jpg",

    process.env.PUBLIC_URL + "/quran/para-12/page-135.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-136.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-137.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-138.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-139.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-140.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-141.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-142.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-143.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-144.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-145.jpg",
    process.env.PUBLIC_URL + "/quran/para-12/page-146.jpg",

    process.env.PUBLIC_URL + "/quran/para-13/page-147.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-148.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-149.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-150.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-151.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-152.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-153.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-154.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-155.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-156.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-157.jpg",
    process.env.PUBLIC_URL + "/quran/para-13/page-158.jpg",

    process.env.PUBLIC_URL + "/quran/para-14/page-159.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-160.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-161.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-162.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-163.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-164.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-165.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-166.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-167.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-168.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-169.jpg",
    process.env.PUBLIC_URL + "/quran/para-14/page-170.jpg",

    process.env.PUBLIC_URL + "/quran/para-15/page-171.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-172.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-173.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-174.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-175.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-176.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-177.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-178.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-179.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-180.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-181.jpg",
    process.env.PUBLIC_URL + "/quran/para-15/page-182.jpg",

    process.env.PUBLIC_URL + "/quran/para-16/page-183.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-184.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-185.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-186.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-187.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-188.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-189.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-190.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-191.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-192.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-193.jpg",
    process.env.PUBLIC_URL + "/quran/para-16/page-194.jpg",

    process.env.PUBLIC_URL + "/quran/para-17/page-195.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-196.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-197.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-198.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-199.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-200.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-201.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-202.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-203.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-204.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-205.jpg",
    process.env.PUBLIC_URL + "/quran/para-17/page-206.jpg",

    process.env.PUBLIC_URL + "/quran/para-18/page-207.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-208.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-209.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-210.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-211.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-212.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-213.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-214.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-215.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-216.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-217.jpg",
    process.env.PUBLIC_URL + "/quran/para-18/page-218.jpg",

    process.env.PUBLIC_URL + "/quran/para-19/page-219.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-220.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-221.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-222.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-223.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-224.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-225.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-226.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-227.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-228.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-229.jpg",
    process.env.PUBLIC_URL + "/quran/para-19/page-230.jpg",

    process.env.PUBLIC_URL + "/quran/para-20/page-231.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-232.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-233.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-234.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-235.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-236.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-237.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-238.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-239.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-240.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-241.jpg",
    process.env.PUBLIC_URL + "/quran/para-20/page-242.jpg",

    process.env.PUBLIC_URL + "/quran/para-21/page-243.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-244.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-245.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-246.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-247.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-248.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-249.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-250.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-251.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-252.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-253.jpg",
    process.env.PUBLIC_URL + "/quran/para-21/page-254.jpg",

    process.env.PUBLIC_URL + "/quran/para-22/page-255.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-256.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-257.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-258.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-259.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-260.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-261.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-262.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-263.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-264.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-265.jpg",
    process.env.PUBLIC_URL + "/quran/para-22/page-266.jpg",

    process.env.PUBLIC_URL + "/quran/para-23/page-267.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-268.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-269.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-270.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-271.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-272.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-273.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-274.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-275.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-276.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-277.jpg",
    process.env.PUBLIC_URL + "/quran/para-23/page-278.jpg",

    process.env.PUBLIC_URL + "/quran/para-24/page-279.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-280.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-281.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-282.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-283.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-284.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-285.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-286.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-287.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-288.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-289.jpg",
    process.env.PUBLIC_URL + "/quran/para-24/page-290.jpg",

    process.env.PUBLIC_URL + "/quran/para-25/page-291.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-292.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-293.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-294.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-295.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-296.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-297.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-298.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-299.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-300.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-301.jpg",
    process.env.PUBLIC_URL + "/quran/para-25/page-302.jpg",

    process.env.PUBLIC_URL + "/quran/para-26/page-303.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-304.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-305.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-306.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-307.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-308.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-309.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-310.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-311.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-312.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-313.jpg",
    process.env.PUBLIC_URL + "/quran/para-26/page-314.jpg",

    process.env.PUBLIC_URL + "/quran/para-27/page-315.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-316.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-317.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-318.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-319.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-320.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-321.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-322.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-323.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-324.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-325.jpg",
    process.env.PUBLIC_URL + "/quran/para-27/page-326.jpg",

    process.env.PUBLIC_URL + "/quran/para-28/page-327.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-328.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-329.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-330.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-331.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-332.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-333.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-334.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-335.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-336.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-337.jpg",
    process.env.PUBLIC_URL + "/quran/para-28/page-338.jpg",

    process.env.PUBLIC_URL + "/quran/para-29/page-339.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-340.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-341.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-342.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-343.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-344.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-345.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-346.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-347.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-348.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-349.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-350.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-351.jpg",
    process.env.PUBLIC_URL + "/quran/para-29/page-352.jpg",

    process.env.PUBLIC_URL + "/quran/para-30/page-353.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-354.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-355.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-356.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-357.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-358.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-359.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-360.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-361.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-362.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-363.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-364.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-365.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-366.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-367.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-368.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-369.jpg",
    process.env.PUBLIC_URL + "/quran/para-30/page-370.jpg",
    
  ];
 const pageWidth = 574;
 const pageHeight = 800;
  return (
    <div style={{ textAlign: "center", marginTop: "20px", maxWidth:1140, margin:'auto', overflow:"hidden",direction:'rtl' }}>
      <HTMLFlipBook
        width={574}
        height={800}
        size="stretch"
        minWidth={315}
        minHeight={420}
        maxWidth={574}
        maxHeight={800}
        drawShadow={true}
        showCover={true}
        mobileScrollSupport={true}
        flippingTime={800}
        startPage={0}
        direction="rtl" // ✅ Enables Right-to-Left flipping
        style={{ display: "flex", justifyContent: "center", alignItems: "center" }} // ✅ Center the flipbook

      >
        {pages.map((page, index) => (
          <div className="page" key={index}>
            <img src={page} alt={`Page ${index + 1}`} height={800} width={574} />
          </div>
        ))}
      </HTMLFlipBook>
    </div>
  );
};

export default QuranPageFlip;
